# Generated by Django 4.2.6 on 2023-11-08 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_tipoestado_tiposubida_manga2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga3',
            fields=[
                ('idManga', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombreManga', models.CharField(max_length=50)),
                ('ano_publicacion', models.CharField(max_length=50)),
                ('mangaka', models.CharField(max_length=50)),
                ('sinopsis', models.CharField(max_length=500)),
                ('editorial', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='D:\\Django Proyectos\\Gatsu\\portada')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.tipoestado')),
                ('tsubida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.tiposubida')),
            ],
        ),
    ]
