# Generated by Django 4.2.6 on 2023-11-08 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_alter_manga3_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetImagen',
            fields=[
                ('idLote', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('capitulo', models.CharField(max_length=50)),
                ('grupoImagen', models.ImageField(upload_to='D:\\Django Proyectos\\Gatsu\\static\\images')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga3')),
            ],
        ),
        migrations.DeleteModel(
            name='Manga2',
        ),
    ]
