# Generated by Django 4.2.7 on 2023-11-13 21:41

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_setimagen_delete_manga2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\GatsuFinal\\Gatsu\\static/images'), upload_to='manga/capitulos/')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='manga.capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='MangaGatsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio_publicacion', models.IntegerField()),
                ('tipo_subida', models.CharField(max_length=20)),
                ('mangaka', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('editorial', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('portada', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\GatsuFinal\\Gatsu\\static/images'), upload_to='manga/portadas/')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangagatsu')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='manga3',
            name='imagen',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\GatsuFinal\\Gatsu\\static/images'), upload_to='images'),
        ),
        migrations.DeleteModel(
            name='SetImagen',
        ),
        migrations.AddField(
            model_name='registropago',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.usuario'),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='manga.mangagatsu'),
        ),
    ]
