# Generated by Django 4.2.7 on 2023-11-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_administrador_capitulo_comentario_imagen_mangagatsu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangagatsu',
            name='anio_publicacion',
            field=models.DateField(),
        ),
    ]
