# Generated by Django 4.2.7 on 2023-11-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_alter_mangagatsu_anio_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangagatsu',
            name='tipo_subida',
            field=models.CharField(choices=[('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
