# Generated by Django 4.2.7 on 2023-11-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_alter_mangagatsu_tipo_subida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangaka', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mangagatsu',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='mangagatsu',
            name='mangaka',
        ),
        migrations.AddField(
            model_name='mangagatsu',
            name='revista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manga.revista'),
        ),
    ]
