# Generated by Django 4.2.7 on 2023-11-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_revista_remove_mangagatsu_editorial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revista',
            old_name='editorial',
            new_name='editoriales',
        ),
    ]
