# Generated by Django 4.2.7 on 2023-11-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_rename_editorial_revista_editoriales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangagatsu',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='mangagatsu',
            name='revista',
        ),
        migrations.RemoveField(
            model_name='revista',
            name='mangaka',
        ),
        migrations.AlterField(
            model_name='mangagatsu',
            name='genero',
            field=models.CharField(choices=[('Accion', 'Acción'), ('Aventura', 'Aventura'), ('Comedia', 'Comedia')], max_length=50),
        ),
        migrations.CreateModel(
            name='NombreManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mangaka', models.CharField(max_length=100)),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.revista')),
            ],
        ),
        migrations.AddField(
            model_name='mangagatsu',
            name='nombre_manga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manga.nombremanga'),
        ),
    ]
