# Generated by Django 4.2.7 on 2023-11-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0012_rename_nombre_nombremanga_nombremanga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangagatsu',
            name='estado',
            field=models.CharField(choices=[('Publicacion', 'Publicación'), ('Finalizado', 'Finalizado'), ('Pausado', 'Pausado'), ('En Hiato', 'En Hiato'), ('En Curso', 'En Curso')], max_length=20),
        ),
    ]
