# Generated by Django 4.2.7 on 2023-11-13 23:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0013_alter_mangagatsu_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangagatsu',
            name='genero',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Accion', 'Acción'), ('Aventura', 'Aventura'), ('Ciencia Ficcion', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Fantasia', 'Fantasía'), ('Harem', 'Harem'), ('Horror', 'Terror'), ('Mecha', 'Mecha')], max_length=15),
        ),
    ]
