# Generated by Django 4.2.6 on 2023-11-30 19:28

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga', '0021_estadisticaslecturacapitulo_estadisticaslecturamanga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenPerfil', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Tesis\\Gatsu-Proyecto\\static/images'), upload_to='perfil/')),
                ('favoritos', models.ManyToManyField(blank=True, to='manga.mangagatsu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
