# Generated by Django 4.2.7 on 2023-12-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0021_estadisticaslecturacapitulo_estadisticaslecturamanga_and_more'),
    ]

    operations = [
    ]
