# Generated by Django 4.2.6 on 2023-11-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0023_perfilusuario_delete_perfil_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='manga_favorito',
            new_name='manga',
        ),
    ]
