# Generated by Django 4.2.7 on 2023-12-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0023_remove_comentario_capitulo_comentario_manga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='manga.mangagatsu'),
        ),
    ]
