# Generated by Django 4.2.6 on 2023-12-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0028_readingprogress2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress2',
            name='capitulo',
        ),
        migrations.RemoveField(
            model_name='readingprogress2',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='readingprogress2',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReadingProgress',
        ),
        migrations.DeleteModel(
            name='ReadingProgress2',
        ),
    ]
