# Generated by Django 4.2.6 on 2023-12-02 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga', '0029_remove_readingprogress2_capitulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.capitulo')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangagatsu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
