# Generated by Django 4.2.6 on 2023-12-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0024_alter_valoracion_manga'),
        ('manga', '0031_alter_progress_user'),
    ]

    operations = [
    ]
