# Generated by Django 4.2.6 on 2023-12-06 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0032_merge_20231203_2219'),
        ('manga', '0032_merge_20231205_2205'),
    ]

    operations = [
    ]
