<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-12-06 01:05
=======
# Generated by Django 4.2.7 on 2023-12-04 01:19
>>>>>>> a9bacb6967bc30a6913b3984a52c6b651353de1e

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('manga', '0032_merge_20231205_2205'),
=======
        ('manga', '0032_merge_20231203_2219'),
>>>>>>> a9bacb6967bc30a6913b3984a52c6b651353de1e
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
<<<<<<< HEAD
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Tesis\\Gatsu-Proyecto\\static/images'), upload_to='manga/capitulos/'),
=======
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ramir\\OneDrive\\Escritorio\\Gatsu-Proyecto\\static/images'), upload_to='manga/capitulos/'),
>>>>>>> a9bacb6967bc30a6913b3984a52c6b651353de1e
        ),
        migrations.AlterField(
            model_name='manga3',
            name='imagen',
<<<<<<< HEAD
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Tesis\\Gatsu-Proyecto\\static/images'), upload_to='images'),
=======
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ramir\\OneDrive\\Escritorio\\Gatsu-Proyecto\\static/images'), upload_to='images'),
>>>>>>> a9bacb6967bc30a6913b3984a52c6b651353de1e
        ),
        migrations.AlterField(
            model_name='mangagatsu',
            name='portada',
<<<<<<< HEAD
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Tesis\\Gatsu-Proyecto\\static/images'), upload_to='manga/portadas/'),
=======
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ramir\\OneDrive\\Escritorio\\Gatsu-Proyecto\\static/images'), upload_to='manga/portadas/'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='imagenPerfil',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ramir\\OneDrive\\Escritorio\\Gatsu-Proyecto\\static/images'), upload_to='perfil/'),
>>>>>>> a9bacb6967bc30a6913b3984a52c6b651353de1e
        ),
    ]
