# Generated by Django 4.2.7 on 2023-11-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0011_remove_mangagatsu_nombre_remove_mangagatsu_revista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nombremanga',
            old_name='nombre',
            new_name='nombreManga',
        ),
    ]
