# Generated by Django 4.2.7 on 2023-11-20 01:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0019_alter_imagen_imagen_alter_manga3_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ramir\\OneDrive\\Escritorio\\Gatsu-Proyecto\\static/images'), upload_to='manga/capitulos/'),
        ),
        migrations.AlterField(
            model_name='manga3',
            name='imagen',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ramir\\OneDrive\\Escritorio\\Gatsu-Proyecto\\static/images'), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mangagatsu',
            name='portada',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ramir\\OneDrive\\Escritorio\\Gatsu-Proyecto\\static/images'), upload_to='manga/portadas/'),
        ),
    ]
